// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fdagwr_test_function
void fdagwr_test_function(std::string input_string);
RcppExport SEXP _fdagwr_fdagwr_test_function(SEXP input_stringSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type input_string(input_stringSEXP);
    fdagwr_test_function(input_string);
    return R_NilValue;
END_RCPP
}
// fmsgwr
Rcpp::List fmsgwr(double input_el, //Rcpp::NumericVector x_points, //Rcpp::NumericMatrix distances_events, //Rcpp::NumericMatrix distances_stations, Rcpp::Nullable<int> num_threads);
RcppExport SEXP _fdagwr_fmsgwr(SEXP input_elSEXP, SEXP x_pointsSEXP, SEXP distances_eventsSEXP, SEXP distances_stationsSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type input_el(input_elSEXP);
    Rcpp::traits::input_parameter< //Rcpp::NumericVector >::type x_points(x_pointsSEXP);
    Rcpp::traits::input_parameter< //Rcpp::NumericMatrix >::type distances_events(distances_eventsSEXP);
    Rcpp::traits::input_parameter< //Rcpp::NumericMatrix >::type distances_stations(distances_stationsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fmsgwr(input_el, x_points, distances_events, distances_stations, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// fsgwr
Rcpp::List fsgwr(double input_el, Rcpp::Nullable<int> num_threads);
RcppExport SEXP _fdagwr_fsgwr(SEXP input_elSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type input_el(input_elSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fsgwr(input_el, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// fgwr
Rcpp::List fgwr(double input_el, Rcpp::Nullable<int> num_threads);
RcppExport SEXP _fdagwr_fgwr(SEXP input_elSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type input_el(input_elSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fgwr(input_el, num_threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fdagwr_fdagwr_test_function", (DL_FUNC) &_fdagwr_fdagwr_test_function, 1},
    {"_fdagwr_fmsgwr", (DL_FUNC) &_fdagwr_fmsgwr, 5},
    {"_fdagwr_fsgwr", (DL_FUNC) &_fdagwr_fsgwr, 2},
    {"_fdagwr_fgwr", (DL_FUNC) &_fdagwr_fgwr, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_fdagwr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
