# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fdagwr_test_function <- function(input_string) {
    .Call(`_fdagwr_fdagwr_test_function`, input_string)
}

